<a href="https://colab.research.google.com/github/Rishabh-0408/Data-Science-and-AI/blob/main/Pandas/Pandas_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Dataset link -> https://drive.google.com/file/d/1pFnlb_zSkb4XLUvDs6sHE_xfcO0yMOQc/view?usp=drive_link

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/mtcars2.csv')

In [8]:
df

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [6]:
df.shape

(32, 13)

In [7]:
df.columns

Index(['S.No', 'Unnamed: 1', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec',
       'vs', 'am', 'gear', 'carb'],
      dtype='object')

In [9]:
# df.head - Records from the top
# df.tail - Records from the bottom

# By default , they give 5 records

In [10]:
df.head()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [11]:
df.tail()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [12]:
df.sample()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.44,18.9,1,0,4,4

In [13]:
df.sample(8)

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4

In [14]:
# df.info() - tells us about the non - null values and the datatypes
# df.describe() - tells us about the statistical data

In [15]:
# Null values
# Duplicate value

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S.No        32 non-null     int64
 1   Unnamed: 1  32 non-null     object
 2   mpg         32 non-null     float64
 3   cyl         32 non-null     int64
 4   disp        32 non-null     float64
 5   hp          32 non-null     int64
 6   drat        32 non-null     float64
 7   wt          32 non-null     float64
 8   qsec        29 non-null     float64
 9   vs          32 non-null     int64
 10  am          32 non-null     int64
 11  gear        32 non-null     int64
 12  carb        32 non-null     int64
dtypes: float64(5), int64(7), object(1)
memory usage: 3.4+ KB

In [17]:
df.describe()

,S.No,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.0000
mean,16.500000,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.674828,0.437500,0.406250,3.687500,2.8125
std,9.380832,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.780394,0.504016,0.498991,0.737804,1.6152
min,1.000000,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,8.750000,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.870000,0.000000,0.000000,3.000000,2.0000
50%,16.500000,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.420000,0.000000,0.000000,4.000000,2.0000
75%,24.250000,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.600000,1.000000,1.000000,4.000000,4.0000
max,32.000000,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [18]:
# How to check the null value
df.isnull()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,True,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,True,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,True,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False

In [19]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [20]:
df.isnull().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          3
vs            0
am            0
gear          0
carb          0
dtype: int64

In [21]:
df.isnull().sum().sum()

np.int64(3)

In [22]:
df.duplicated().sum()

np.int64(0)