<a href="https://colab.research.google.com/github/Rishabh-0408/Data-Science-and-AI/blob/main/Pandas/Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Agenda - Pandas Theory(Concepts)

In [ ]:
# Pandas - Python Data Analysis Library

In [ ]:
# Used for Data analysis and manipulation
# Works well with tabular data (rows and columns)
# Pandas is actually built upon numpy
# Cleaning data
# EDA(Exploratory Data Analysis)
# Null values , Duplicate values

In [ ]:
# Numpy - 50k records
# Pandas - 500k records

In [ ]:
# Series
# Dataframes

In [ ]:
# Series - 1D data , 1 particular column
# Dataframes - 2D data , excel sheet

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Series

data = [10,20,30,"Vamsi","Pratik"]
s1 = pd.Series(data)
s1

0        10
1        20
2        30
3     Vamsi
4    Pratik
dtype: object

In [ ]:
s2 = pd.Series(["Karan","Krish","Kishan","Shyam","John"])
s2

0     Karan
1     Krish
2    Kishan
3     Shyam
4      John
dtype: object

In [ ]:
data = ["Karan","Krish","Kishan","Shyam","John"]
s22 = pd.Series(data , index = ["name1","name2","nam3","name4","name5"])
s22

name1     Karan
name2     Krish
nam3     Kishan
name4     Shyam
name5      John
dtype: object

In [ ]:
# Indexing

b = pd.Series([10,20,30],name = "Score")
b

In [3]:
# Dataframe

data = [["krishna",67,"male"],["rishabh",89,"male"],['jancy',90,"female"],['shwan',22,'Female']]
df = pd.DataFrame(data)
df

         0   1       2
0  krishna  67    male
1  rishabh  89    male
2    jancy  90  female
3    shwan  22  Female

In [4]:
data = [["krishna",67,"male"],["rishabh",89,"male"],['jancy',90,"female"],['shwan',22,'Female']]
df = pd.DataFrame(data,columns=['Name',"marks","gender"])
df

      Name  marks  gender
0  krishna     67    male
1  rishabh     89    male
2    jancy     90  female
3    shwan     22  Female

In [9]:
# Set_index help to set a column as index
data = {
    "Name": ["Ram","Shyam","Kishan","Bob"],
    "Age": [21,25,45,32],
    "Marks": [90,82,85,54]
}
df = pd.DataFrame(data)
df = df.set_index('Name')
df

        Age  Marks
Name
Ram      21     90
Shyam    25     82
Kishan   45     85
Bob      32     54

In [12]:
# loc / iloc

# loc - label based indexing(string)
# iloc - Position based indexing(numerical)

In [10]:
data = {
    "Name": ["Ram","Shyam","Kishan","Bob"],
    "Age": [21,25,45,32],
    "Marks": [90,82,85,54]
}
df = pd.DataFrame(data, index=['a','b','c','d'])
df

     Name  Age  Marks
a     Ram   21     90
b   Shyam   25     82
c  Kishan   45     85
d     Bob   32     54

In [11]:
df.loc['b']

Name     Shyam
Age         25
Marks       82
Name: b, dtype: object

In [13]:
df.loc["a":"d"]

     Name  Age  Marks
a     Ram   21     90
b   Shyam   25     82
c  Kishan   45     85
d     Bob   32     54

In [14]:
df.loc["b","Age"]

np.int64(25)

In [15]:
df.loc["a":"c","Name":"Age"]

     Name  Age
a     Ram   21
b   Shyam   25
c  Kishan   45

In [16]:
df.loc["a":"c","Name":"Marks"]

     Name  Age  Marks
a     Ram   21     90
b   Shyam   25     82
c  Kishan   45     85

In [17]:
df.loc["a":"c",("Name","Marks")]

     Name  Marks
a     Ram     90
b   Shyam     82
c  Kishan     85

In [20]:
# Filtering

df.loc[df["Marks"]>80]
# Filter those students who have scored marks higher than 80

     Name  Age  Marks
a     Ram   21     90
b   Shyam   25     82
c  Kishan   45     85

In [21]:
df.loc[(df["Marks"]>80) & (df["Age"]>30)]

     Name  Age  Marks
c  Kishan   45     85

In [22]:
df.loc[(df["Marks"]>80) | (df["Age"]>30)]

     Name  Age  Marks
a     Ram   21     90
b   Shyam   25     82
c  Kishan   45     85
d     Bob   32     54

In [24]:
# iloc  = Position (numerical ) based indexing

In [23]:
df.iloc[1]  # 0 -a , 1 - b , 2 - c , 3 - d

Name     Shyam
Age         25
Marks       82
Name: b, dtype: object

In [25]:
# i can use either loc / iloc to access the records of my dataframe
# we can use iloc in case we have not specified lable or index

In [26]:
df.iloc[1:4, 0:2]

     Name  Age
b   Shyam   25
c  Kishan   45
d     Bob   32

In [31]:
df.iloc[2:4,0:3] # n-1 rule is applied here

     Name  Age  Marks
c  Kishan   45     85
d     Bob   32     54