<a href="https://colab.research.google.com/github/Rishabh-0408/Data-Science-and-AI/blob/main/Pandas/Pandas_Handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [ ]:
# Create a list , tuple , set , with elements from 1 to 10
# Create a list of indexes [a,b,c,.....j]
# Convert each of these into pandas Series

In [ ]:
list1 =[1,2,3,4,5,6,7,8,9,10]
tuple1 =(1,2,3,4,5,6,7,8,9,10)
set1 = {1,2,3,4,5,6,7,8,9,10}

ind = ['a','b','c','d','e','f','g','h','i','j']

In [ ]:
l1 = pd.Series(list1, index = ind)
l1

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
t1 = pd.Series(tuple1, index = ind)
t1

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
s1 = pd.Series(set1, index = ind)
s1

TypeError: 'set' type is unordered

In [ ]:
# set is unordered so indexing is not possible

In [ ]:
s1 = pd.Series(list(set1), index = ind)
s1

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
# Create a dictionary with 5 key- value pairs
# Convert the dict into a pandas Series

In [ ]:
dict1 = {
    'Apple' : 10,
    'Banana' : 20,
    'Mango' : 30,
    'Kiwi' : 20,
    'Lichi' : 40
}
dict1

{'Apple': 10, 'Banana': 20, 'Mango': 30, 'Kiwi': 20, 'Lichi': 40}

In [ ]:
d1 = pd.Series(dict1)
d1

Apple     10
Banana    20
Mango     30
Kiwi      20
Lichi     40
dtype: int64

In [ ]:
# Create a sample series with 10 numbers
# print the first 5 elements
# print the last 5 elements
# update the 5th index with value 200
# Delete the first element (.drop)

In [ ]:
data = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(data.head())
print(data.tail())

0    1
1    2
2    3
3    4
4    5
dtype: int64
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
data[5] = 200
print(data)

0      1
1      2
2      3
3      4
4      5
5    200
6      7
7      8
8      9
9     10
dtype: int64

In [ ]:
data = data.drop(0)
print(data)

1      2
2      3
3      4
4      5
5    200
6      7
7      8
8      9
9     10
dtype: int64

In [ ]:
# Create a nested list  and  dict(store the value in the form of a list) , create at least 3 keys
# Convert both of them into a DataFrame

In [ ]:
nes_list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ]
print(nes_list)
nes_dict = {
    'Name':['r1','r3','r2'],
    'age':[22,12,23],
    'city':['bangalore','pune','oune'],
    'job':['NA','NA','NA'],
    'email':['random@eail','random@eail','random@eail']
    }
print('\n', nes_dict)
# Convert both of them into a DataFrame
df_list = pd.DataFrame(nes_list)
print('\n',df_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

 {'Name': ['r1', 'r3', 'r2'], 'age': [22, 12, 23], 'city': ['bangalore', 'pune', 'oune'], 'job': ['NA', 'NA', 'NA'], 'email': ['random@eail', 'random@eail', 'random@eail']}

In [3]:
dict1 = {
    "Car-Model": ["Audi","BMW","Maruti","KIA"],
    "Price": [100000, 200000 ,340000,7800000],
    "Year" : [2012,2015,2025,2023]
}
df2 = pd.DataFrame(dict1)
df2

  Car-Model    Price  Year
0      Audi   100000  2012
1       BMW   200000  2015
2    Maruti   340000  2025
3       KIA  7800000  2023

In [4]:
# Rename the column name from Car - Model to Model
df2.rename(columns = {"Car-Model":"Model"},inplace = True)
# To make the change permanent , inplace = True

In [5]:
df2

    Model    Price  Year
0    Audi   100000  2012
1     BMW   200000  2015
2  Maruti   340000  2025
3     KIA  7800000  2023

In [ ]:
# Select the records where the model is BMW and the year is greater than 2012
# Select the records where the model is BMW or the year is greater than or equal to 2010
# Select the records where the year is greater than 2012

In [8]:
df2.loc[(df2['Model'] == 'BMW') & (df2['Year'] > 2012)]

  Model   Price  Year
1   BMW  200000  2015

In [9]:
df2.loc[(df2['Model'] == 'BMW') & (df2['Year'] >= 2010)]

  Model   Price  Year
1   BMW  200000  2015

In [10]:
df2.loc[(df2['Year'] > 2012)]

    Model    Price  Year
1     BMW   200000  2015
2  Maruti   340000  2025
3     KIA  7800000  2023

In [ ]:
# Dataset -> https://drive.google.com/file/d/1N8VT6q52qjHwhjYDQ7mB_LpMi-gAtVP2/view?usp=drive_link

In [11]:
df = pd.read_csv('/content/adult_data (1).csv')

In [13]:
df

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...
995,56,Private,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,55,United-States,>50K
996,45,Private,Masters,Divorced,Prof-specialty,Not-in-family,White,Male,45,United-States,<=50K
997,48,Federal-gov,Bachelors,Divorced,Exec-managerial,Unmarried,White,Male,58,United-States,>50K
998,40,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,<=50K
999,39,Self-emp-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,50,United-States,>50K

In [ ]:
# Do a basic analysis of the dataset
# Check for the top 7 records and bottom 7 records
# create a sample of 10 random records

In [18]:
df.head()

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K

In [19]:
df.tail()

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
995,56,Private,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,55,United-States,>50K
996,45,Private,Masters,Divorced,Prof-specialty,Not-in-family,White,Male,45,United-States,<=50K
997,48,Federal-gov,Bachelors,Divorced,Exec-managerial,Unmarried,White,Male,58,United-States,>50K
998,40,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,<=50K
999,39,Self-emp-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,50,United-States,>50K

In [20]:
df.shape

(1000, 11)

In [21]:
df.columns

Index(['age', 'workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'hours-per-week', 'native-country',
       'income'],
      dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             1000 non-null   int64
 1   workclass       938 non-null    object
 2   education       1000 non-null   object
 3   marital-status  1000 non-null   object
 4   occupation      938 non-null    object
 5   relationship    1000 non-null   object
 6   race            1000 non-null   object
 7   sex             1000 non-null   object
 8   hours-per-week  1000 non-null   int64
 9   native-country  982 non-null    object
 10  income          1000 non-null   object
dtypes: int64(2), object(9)
memory usage: 86.1+ KB

In [25]:
df.describe()

              age  hours-per-week
count  1000.00000     1000.000000
mean     38.05100       39.876000
std      13.34948       12.018114
min      17.00000        1.000000
25%      28.00000       40.000000
50%      36.00000       40.000000
75%      46.00000       45.000000
max      90.00000       99.000000

In [27]:
df.isnull()

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False

In [26]:
df.isnull().sum().sum()

np.int64(142)

In [32]:
df.isnull().sum() # Count of null values per column

age                0
workclass         62
education          0
marital-status     0
occupation        62
relationship       0
race               0
sex                0
hours-per-week     0
native-country    18
income             0
dtype: int64

In [29]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [30]:
df.duplicated().sum()

np.int64(9)

In [31]:
df.sample(10)

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,income
498,26,Private,Some-college,Never-married,Prof-specialty,Not-in-family,White,Female,35,United-States,<=50K
975,25,Private,Some-college,Never-married,Sales,Not-in-family,White,Female,40,United-States,<=50K
613,26,Local-gov,Bachelors,Never-married,Prof-specialty,Own-child,White,Male,40,United-States,<=50K
725,43,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,40,NaN,>50K
819,47,Private,HS-grad,Married-civ-spouse,Transport-moving,Husband,White,Male,50,United-States,>50K
948,43,Private,Some-college,Divorced,Craft-repair,Unmarried,White,Male,35,United-States,<=50K
704,46,Private,Doctorate,Divorced,Prof-specialty,Unmarried,White,Female,65,United-States,>50K
161,25,Private,HS-grad,Never-married,Other-service,Unmarried,White,Female,40,United-States,<=50K
143,45,Private,Assoc-voc,Never-married,Prof-specialty,Not-in-family,White,Female,40,United-States,>50K
447,51,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,Amer-Indian-Eskimo,Male,40,United-States,<=50K